# Build-time runtime discovery. Included only by enabled Linux/Windows hosts.
execute_process(COMMAND "${SWITCH2KIT_SWIFTC}" -print-target-info
  OUTPUT_VARIABLE _s2k_runtime_info COMMAND_ERROR_IS_FATAL ANY)
string(JSON _s2k_count LENGTH "${_s2k_runtime_info}" paths runtimeLibraryPaths)
set(_s2k_runtime_paths)
if(_s2k_count GREATER 0)
  math(EXPR _s2k_last "${_s2k_count} - 1")
  foreach(_index RANGE 0 ${_s2k_last})
    string(JSON _path GET "${_s2k_runtime_info}" paths runtimeLibraryPaths ${_index})
    file(TO_CMAKE_PATH "${_path}" _path)
    if(IS_DIRECTORY "${_path}")
      list(APPEND _s2k_runtime_paths "${_path}")
    endif()
  endforeach()
endif()
if(NOT _s2k_runtime_paths)
  message(FATAL_ERROR "The selected Swift compiler did not identify runtime library directories")
endif()
get_filename_component(_s2k_swift_bin "${SWITCH2KIT_SWIFTC}" DIRECTORY)
find_file(SWITCH2KIT_SWIFT_LICENSE LICENSE.txt
  PATHS "${_s2k_swift_bin}/../share/swift" NO_DEFAULT_PATH)
find_program(_s2k_git git REQUIRED)
string(JSON _s2k_compiler_version GET "${_s2k_runtime_info}" compilerVersion)
if(_s2k_compiler_version MATCHES "Swift version 6\\.2\\.1([ (]|$)")
  set(_s2k_swift_tag swift-6.2.1-RELEASE)
  set(_s2k_icu_tag release-74-1)
  set(_s2k_icu_blob 9f54372febca06e134bbc9d4700a1ebfeda13843)
elseif(_s2k_compiler_version MATCHES "Swift version 6\\.3\\.3([ (]|$)")
  set(_s2k_swift_tag swift-6.3.3-RELEASE)
  set(_s2k_icu_tag release-76-1)
  set(_s2k_icu_blob 180db98fcc66ca7797940b7fad5a7f3987d9f145)
endif()
set(SWITCH2KIT_RUNTIME_ICU_LICENSE "" CACHE FILEPATH
    "Explicit ICU license/third-party notices for a different Swift runtime distribution")
if(WIN32)
  find_program(_s2k_inspector dumpbin REQUIRED)
  set(_s2k_platform "windows+pe")
  set(_s2k_inspector_kind dumpbin)
else()
  find_program(_s2k_inspector objdump REQUIRED)
  find_program(_s2k_readelf readelf REQUIRED)
  set(_s2k_platform "linux+elf")
  set(_s2k_inspector_kind objdump)
endif()
set(SWITCH2KIT_RUNTIME_CONFIG "${CMAKE_CURRENT_BINARY_DIR}/Switch2KitRuntimePaths.cmake"
    CACHE INTERNAL "Build-only Swift runtime deployment inputs")
file(CONFIGURE OUTPUT "${SWITCH2KIT_RUNTIME_CONFIG}" CONTENT [=[
set(S2K_RUNTIME_DIRS [==[@_s2k_runtime_paths@]==])
set(S2K_SWIFT_LICENSE [==[@SWITCH2KIT_SWIFT_LICENSE@]==])
set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM "@_s2k_platform@")
set(CMAKE_GET_RUNTIME_DEPENDENCIES_TOOL "@_s2k_inspector_kind@")
set(CMAKE_GET_RUNTIME_DEPENDENCIES_COMMAND [==[@_s2k_inspector@]==])
set(S2K_READELF [==[@_s2k_readelf@]==])
set(S2K_GIT [==[@_s2k_git@]==])
set(S2K_SWIFT_TAG "@_s2k_swift_tag@")
set(S2K_ICU_TAG "@_s2k_icu_tag@")
set(S2K_ICU_BLOB "@_s2k_icu_blob@")
set(S2K_ICU_LICENSE [==[@SWITCH2KIT_RUNTIME_ICU_LICENSE@]==])
set(S2K_COMPILER_VERSION [==[@_s2k_compiler_version@]==])
]=] @ONLY)
set(SWITCH2KIT_RUNTIME_SCRIPT "${CMAKE_CURRENT_LIST_DIR}/StageDesktopRuntime.cmake"
    CACHE INTERNAL "Swift runtime deployment script")
