cmake_minimum_required(VERSION 3.24)
if(POLICY CMP0207)
  cmake_policy(SET CMP0207 NEW)
endif()
# Operate on application-owned copies, never on the compiler installation.
foreach(_argument S2K_LIBRARY S2K_DESTINATION S2K_NOTICES S2K_RUNTIME_CONFIG)
  if(NOT DEFINED ${_argument} OR "${${_argument}}" STREQUAL "")
    message(FATAL_ERROR "Runtime deployment requires ${_argument}")
  endif()
endforeach()
include("${S2K_RUNTIME_CONFIG}")
# The facade is not the only Swift client: a linked host/plugin/fixture can
# import runtime libraries that an optimized facade does not reference.
set(_application_libraries "${S2K_LIBRARY}" ${S2K_EXTRA_LIBRARIES})
list(REMOVE_DUPLICATES _application_libraries)
set(_application_directories)
foreach(_library IN LISTS _application_libraries)
  if(NOT EXISTS "${_library}" OR IS_DIRECTORY "${_library}")
    message(FATAL_ERROR "A built application library is required: ${_library}")
  endif()
  get_filename_component(_directory "${_library}" DIRECTORY)
  list(APPEND _application_directories "${_directory}")
endforeach()
set(_executables)
if(DEFINED S2K_EXECUTABLE AND NOT S2K_EXECUTABLE STREQUAL "")
  if(NOT EXISTS "${S2K_EXECUTABLE}" OR IS_DIRECTORY "${S2K_EXECUTABLE}")
    message(FATAL_ERROR "The built host executable is required: ${S2K_EXECUTABLE}")
  endif()
  list(APPEND _executables "${S2K_EXECUTABLE}")
  get_filename_component(_directory "${S2K_EXECUTABLE}" DIRECTORY)
  list(APPEND _application_directories "${_directory}")
endif()
list(REMOVE_DUPLICATES _application_directories)
# Stop at files actually resolved inside the Windows installation. Filtering
# names before resolution would also hide missing application DLLs. Filtering
# after this traversal would be too late: OS internals can have optional imports
# and another copy of the C++ runtime, neither belonging in the Swift closure.
set(_system_libraries)
foreach(_directory IN LISTS S2K_SYSTEM_RUNTIME_DIRS)
  file(GLOB _libraries LIST_DIRECTORIES false "${_directory}/*.[dD][lL][lL]")
  list(APPEND _system_libraries ${_libraries})
endforeach()
set(_scan_libraries ${_application_libraries})
set(_scan_executables ${_executables})
set(_scan_directories ${_application_directories} ${S2K_RUNTIME_DIRS} ${S2K_SYSTEM_RUNTIME_DIRS})
if(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM STREQUAL "windows+pe")
  # Windows searches beside each importing binary before DIRECTORIES. Inspect
  # isolated copies of declared application roots so an old staged runtime
  # cannot mask a missing compiler dependency or conflict with the original.
  # Independent scans must not serialize behind the deployment copy lock.
  get_filename_component(_destination_key "${S2K_DESTINATION}" ABSOLUTE)
  string(TOLOWER "${_destination_key}" _destination_key)
  string(SHA256 _destination_key "${_destination_key}")
  set(_deployment_lock "${S2K_RUNTIME_CONFIG}.${_destination_key}.lock")
  set(_root_names)
  foreach(_root IN LISTS _application_libraries _executables)
    get_filename_component(_name "${_root}" NAME)
    string(TOLOWER "${_name}" _name)
    if(_name IN_LIST _root_names)
      message(FATAL_ERROR "Ambiguous application library/executable name: ${_name}")
    endif()
    list(APPEND _root_names "${_name}")
  endforeach()
  string(RANDOM LENGTH 16 ALPHABET 0123456789abcdef _scan_id)
  set(_scan_root "${S2K_RUNTIME_CONFIG}.scan-${_scan_id}")
  file(MAKE_DIRECTORY "${_scan_root}")
  set(_scan_libraries)
  set(_scan_executables)
  foreach(_kind libraries executables)
    if(_kind STREQUAL "libraries")
      set(_roots ${_application_libraries})
    else()
      set(_roots ${_executables})
    endif()
    foreach(_root IN LISTS _roots)
      get_filename_component(_name "${_root}" NAME)
      file(COPY "${_root}" DESTINATION "${_scan_root}")
      list(APPEND _scan_${_kind} "${_scan_root}/${_name}")
    endforeach()
  endforeach()
  set(_scan_directories "${_scan_root}" ${S2K_RUNTIME_DIRS} ${S2K_SYSTEM_RUNTIME_DIRS})
endif()
file(GET_RUNTIME_DEPENDENCIES
  EXECUTABLES ${_scan_executables}
  LIBRARIES ${_scan_libraries}
  DIRECTORIES ${_scan_directories}
  POST_EXCLUDE_FILES ${_system_libraries}
  PRE_EXCLUDE_REGEXES "^api-ms-" "^ext-ms-"
  RESOLVED_DEPENDENCIES_VAR _resolved
  UNRESOLVED_DEPENDENCIES_VAR _unresolved
  CONFLICTING_DEPENDENCIES_PREFIX _conflicts)
if(_unresolved)
  message(FATAL_ERROR "Unresolved runtime dependencies: ${_unresolved}")
endif()
if(_conflicts_FILENAMES)
  set(_details "")
  foreach(_name IN LISTS _conflicts_FILENAMES)
    string(APPEND _details "\n  ${_name}: ${_conflicts_${_name}}")
  endforeach()
  message(FATAL_ERROR "Ambiguous runtime dependencies:${_details}")
endif()
# License acquisition is build/install work, never an application startup request.
# Git blob validation pins complete upstream license texts, not documentation prose.
include("${CMAKE_CURRENT_LIST_DIR}/RuntimeNotices.cmake")
switch2kit_runtime_notices()
file(REAL_PATH "${S2K_DESTINATION}" _destination)
foreach(_directory IN LISTS S2K_RUNTIME_DIRS)
  file(REAL_PATH "${_directory}" _runtime)
  cmake_path(IS_PREFIX _runtime "${_destination}" NORMALIZE _inside_runtime)
  if(_inside_runtime)
    message(FATAL_ERROR "Refusing to stage runtime libraries into the compiler installation")
  endif()
endforeach()
set(_copies ${_application_libraries})
set(_runtime_libraries)
foreach(_library IN LISTS _resolved)
  file(REAL_PATH "${_library}" _real)
  foreach(_directory IN LISTS S2K_RUNTIME_DIRS)
    file(REAL_PATH "${_directory}" _root)
    # CMake's path-prefix comparison is case-sensitive even on Windows.
    if(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM STREQUAL "windows+pe")
      string(TOLOWER "${_real}" _candidate)
      string(TOLOWER "${_root}" _root)
    else()
      set(_candidate "${_real}")
    endif()
    cmake_path(IS_PREFIX _root "${_candidate}" NORMALIZE _owned)
    if(_owned)
      list(APPEND _runtime_libraries "${_library}")
      break()
    endif()
  endforeach()
endforeach()
if(DEFINED _scan_root)
  file(REMOVE_RECURSE "${_scan_root}")
endif()
if(NOT _runtime_libraries)
  message(FATAL_ERROR "No Swift runtime dependency was resolved inside the selected compiler's runtime directories")
endif()
list(APPEND _copies ${_runtime_libraries})
list(REMOVE_DUPLICATES _copies)
list(LENGTH _copies _count)
# Dependency inspection and license acquisition above operate independently.
# Serialize only the short mutation of shared application-owned output files.
if(DEFINED _deployment_lock)
  file(LOCK "${_deployment_lock}" GUARD PROCESS TIMEOUT 60)
endif()
file(MAKE_DIRECTORY "${S2K_DESTINATION}" "${S2K_NOTICES}/SwiftRuntime")
foreach(_source IN LISTS _copies)
  get_filename_component(_name "${_source}" NAME)
  set(_copy "${S2K_DESTINATION}/${_name}")
  if(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM STREQUAL "windows+pe")
    # Equal timestamps do not prove that an existing DLL has identical bytes.
    file(COPY_FILE "${_source}" "${_copy}" ONLY_IF_DIFFERENT)
  else()
    file(COPY "${_source}" DESTINATION "${S2K_DESTINATION}" FOLLOW_SYMLINK_CHAIN)
  endif()
  if(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM STREQUAL "linux+elf")
    execute_process(COMMAND "${S2K_READELF}" -d "${_copy}"
      OUTPUT_VARIABLE _dynamic COMMAND_ERROR_IS_FATAL ANY)
    string(REGEX MATCH "\\((RUNPATH|RPATH)\\)[^\n]*\\[([^]]*)\\]" _path "${_dynamic}")
    if(_path)
      set(_old "${CMAKE_MATCH_2}")
      if(NOT _old STREQUAL "$ORIGIN")
        file(RPATH_CHANGE FILE "${_copy}" OLD_RPATH "${_old}" NEW_RPATH "$ORIGIN")
      endif()
    endif()
  endif()
endforeach()
file(COPY_FILE "${S2K_SWIFT_LICENSE}" "${S2K_NOTICES}/SwiftRuntime/LICENSE.txt" ONLY_IF_DIFFERENT)
# Retain complete upstream component license and third-party notice texts.
file(COPY_FILE "${S2K_ICU_LICENSE}" "${S2K_NOTICES}/SwiftRuntime/ICU.txt" ONLY_IF_DIFFERENT)
file(WRITE "${S2K_NOTICES}/SwiftRuntime/NOTICE.txt"
  "Swift, Foundation, Dispatch and BlocksRuntime: Apple Inc. and the Swift project authors.\nApache License 2.0 with Runtime Library Exception: LICENSE.txt.\nICU license and third-party notices: ICU.txt.\nCompiler: ${S2K_COMPILER_VERSION}\n")
file(WRITE "${S2K_NOTICES}/SwiftRuntime/deployment.txt"
  "Swift runtime libraries are copied from the compiler-selected runtime directories.\nELF copies have application-relative runtime search paths. System libraries and drivers are not redistributed by this helper.\n")
message(STATUS "Staged ${_count} facade/runtime libraries into ${S2K_DESTINATION}")
