cmake_minimum_required(VERSION 3.24)
# Operate on application-owned copies, never on the compiler installation.
foreach(_argument S2K_LIBRARY S2K_DESTINATION S2K_NOTICES S2K_RUNTIME_CONFIG)
  if(NOT DEFINED ${_argument} OR "${${_argument}}" STREQUAL "")
    message(FATAL_ERROR "Runtime deployment requires ${_argument}")
  endif()
endforeach()
include("${S2K_RUNTIME_CONFIG}")
if(NOT EXISTS "${S2K_LIBRARY}")
  message(FATAL_ERROR "The built facade is required")
endif()
file(GET_RUNTIME_DEPENDENCIES
  LIBRARIES "${S2K_LIBRARY}"
  DIRECTORIES ${S2K_RUNTIME_DIRS}
  PRE_EXCLUDE_REGEXES "^api-ms-" "^ext-ms-"
  RESOLVED_DEPENDENCIES_VAR _resolved
  UNRESOLVED_DEPENDENCIES_VAR _unresolved
  CONFLICTING_DEPENDENCIES_PREFIX _conflicts)
if(_unresolved OR _conflicts_FILENAMES)
  message(FATAL_ERROR "Unresolved/ambiguous runtime dependencies: ${_unresolved};${_conflicts_FILENAMES}")
endif()
# License acquisition is build/install work, never an application startup request.
# Git blob validation pins complete upstream license texts, not documentation prose.
include("${CMAKE_CURRENT_LIST_DIR}/RuntimeNotices.cmake")
switch2kit_runtime_notices()
file(REAL_PATH "${S2K_DESTINATION}" _destination)
foreach(_directory IN LISTS S2K_RUNTIME_DIRS)
  file(REAL_PATH "${_directory}" _runtime)
  cmake_path(IS_PREFIX _runtime "${_destination}" NORMALIZE _inside_runtime)
  if(_inside_runtime)
    message(FATAL_ERROR "Refusing to stage runtime libraries into the compiler installation")
  endif()
endforeach()
file(MAKE_DIRECTORY "${S2K_DESTINATION}" "${S2K_NOTICES}/SwiftRuntime")
set(_copies "${S2K_LIBRARY}")
foreach(_library IN LISTS _resolved)
  file(REAL_PATH "${_library}" _real)
  foreach(_directory IN LISTS S2K_RUNTIME_DIRS)
    file(REAL_PATH "${_directory}" _root)
    # CMake's path-prefix comparison is case-sensitive even on Windows.
    if(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM STREQUAL "windows+pe")
      string(TOLOWER "${_real}" _candidate)
      string(TOLOWER "${_root}" _root)
    else()
      set(_candidate "${_real}")
    endif()
    cmake_path(IS_PREFIX _root "${_candidate}" NORMALIZE _owned)
    if(_owned)
      list(APPEND _copies "${_library}")
      break()
    endif()
  endforeach()
endforeach()
list(REMOVE_DUPLICATES _copies)
list(LENGTH _copies _count)
if(_count LESS 2)
  message(FATAL_ERROR "No Swift runtime dependency was resolved inside the selected compiler's runtime directories")
endif()
foreach(_source IN LISTS _copies)
  get_filename_component(_name "${_source}" NAME)
  file(COPY "${_source}" DESTINATION "${S2K_DESTINATION}" FOLLOW_SYMLINK_CHAIN)
  set(_copy "${S2K_DESTINATION}/${_name}")
  if(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM STREQUAL "linux+elf")
    execute_process(COMMAND "${S2K_READELF}" -d "${_copy}"
      OUTPUT_VARIABLE _dynamic COMMAND_ERROR_IS_FATAL ANY)
    string(REGEX MATCH "\\((RUNPATH|RPATH)\\)[^\n]*\\[([^]]*)\\]" _path "${_dynamic}")
    if(_path)
      set(_old "${CMAKE_MATCH_2}")
      if(NOT _old STREQUAL "$ORIGIN")
        file(RPATH_CHANGE FILE "${_copy}" OLD_RPATH "${_old}" NEW_RPATH "$ORIGIN")
      endif()
    endif()
  endif()
endforeach()
file(COPY_FILE "${S2K_SWIFT_LICENSE}" "${S2K_NOTICES}/SwiftRuntime/LICENSE.txt" ONLY_IF_DIFFERENT)
# Retain complete upstream component license and third-party notice texts.
file(COPY_FILE "${S2K_ICU_LICENSE}" "${S2K_NOTICES}/SwiftRuntime/ICU.txt" ONLY_IF_DIFFERENT)
file(WRITE "${S2K_NOTICES}/SwiftRuntime/NOTICE.txt"
  "Swift, Foundation, Dispatch and BlocksRuntime: Apple Inc. and the Swift project authors.\nApache License 2.0 with Runtime Library Exception: LICENSE.txt.\nICU license and third-party notices: ICU.txt.\nCompiler: ${S2K_COMPILER_VERSION}\n")
file(WRITE "${S2K_NOTICES}/SwiftRuntime/deployment.txt"
  "Swift runtime libraries are copied from the compiler-selected runtime directories.\nELF copies have application-relative runtime search paths. System libraries and drivers are not redistributed by this helper.\n")
message(STATUS "Staged ${_count} facade/runtime libraries into ${S2K_DESTINATION}")
