cmake_minimum_required(VERSION 3.24)
project(Switch2KitHostFileTests LANGUAGES CXX)
enable_testing()
add_executable(host-file main.cpp)
target_compile_features(host-file PRIVATE cxx_std_17)
if(MSVC)
  target_compile_options(host-file PRIVATE /UNDEBUG /utf-8)
else()
  target_compile_options(host-file PRIVATE -UNDEBUG -Wall -Wextra -Werror)
endif()
add_test(NAME host-file COMMAND host-file)
set_tests_properties(host-file PROPERTIES TIMEOUT 20)
